name: notification_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  awesome_notifications: ^0.9.3+1
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/climate.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/
